version: "4.0"

services:
  rabbitmq:
    image: rabbitmq:3.9.7-management
    ports:
      - 5672:5672
      - 15672:15672
  database:
    image: postgres:13
    container_name: parking_meter
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  parking-meter-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - DB_SERVER=database
      - SERVER_PORT=80
    ports:
      - "80:80"